<?xml version="1.0" encoding="utf-8"?>
<!--This file contains strings that must be translated for localized product versions-->
<!DOCTYPE stringtable[
  <!ELEMENT stringtable (string+)>
  <!ELEMENT string (#PCDATA)>
  <!ATTLIST string
                 id CDATA #REQUIRED>


]>
<stringtable>
  <string id="IDS_EF_XML_DUPLICATE_OBJECT__CONVECTION">Convection already exists in the session.</string>
  <string id="IDS_EF_XML_DUPLICATE_OBJECT__MATERIAL">Material already exists in the session.</string>
  <string id="IDS_EF_XML_PARSE_FAILURE__CONVECTION">An error occurred while reading the convection file.</string>
  <string id="IDS_EF_XML_PARSE_FAILURE__MATERIAL">An error occurred while reading the material file.</string>
  <string id="IDS_E_MBD_Cubic_Spline_Fit_Not_Accurate_Enough">
    A curve fit of the tabular data for %1 is inaccurate. (more)

    You can correct this by either:
    a) Inserting a Step at each tabular data time point.
    b) Insert more tabular data points at intermediate time values.
  </string>
  <string id="IDS_FA_BETAWARNING">A beta feature exists in the branch.  "Show Beta Options" must be enabled for the solution to continue.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__LOAD_TRANSFER">An error occurred while loading the LOAD TRANSFER module.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__MESHER">An error occurred while loading the MESHING module.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__POST">An error occurred while loading the POST module.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__POST_FATIGUE">An error occurred while loading the FATIGUE module.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__SOLVER_ENGINE">An error occurred while starting the solver module. Please refer to the Troubleshooting section in the &simproductguidedocumentation; for more information.</string>
  <string id="IDS_FA_DLL_LOAD_FAILURE__SOLVER_WRAPPER">An error occurred while loading the solver module.</string>
  <string id="IDS_FA_FAILURE__FINDING_RESULTS">The result file(*.rst) has insufficient data to compute the requested result</string>
  <string id="IDS_FA_GENERALFAILURE">A general failure occurred during the solution process.</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT_TOOL__INVALID_SCOPING">You have a contact tool with invalid contact selections or result requests</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__BONDED_OR_NO_SEPARATION_TYPE_REQUIRED">BONDED or NO SEPARATION type required for this contact configuration</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__BONDED_TYPE_REQUIRED">Beam formulation on a contact region is only supported if its type is bonded</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__INVALID_EDGE_CONTACT_FORMULATION">Invalid formulation for edge contact</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__INVALID_EDGE_FACE_SCOPING">Faces must be designated as targets in edge-face contact</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__INVALID_INTERFACE_TREATMENT">Invalid interface treatment selected</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__INVALID_USE_OF_MPC_FORMULATION">Invalid use of MPC formulation</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__MISSING_GEOMETRY">Unspecified contact or target geometry in contact region</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__MPC_FORMULATION_REQUIRED">MPC formulation required for edge contact</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__NULL_THERMAL_CONDUCTANCE">Non-zero thermal conductance is required</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__UNDERDEFINED_CONTACT_REGIONS">One or more contact regions are not fully defined</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__UNDERDEFINED_PENETRATION_TOLERANCE">You have one or more contact regions with an invalid penetration tolerance setting.</string>
  <string id="IDS_FA_INPUT_FAILURE_CONTACT__UNDERDEFINED_PINBALL_REGION">You have one or more contact regions with an invalid pinball setting.</string>
  <string id="IDS_FA_INPUT_FAILURE_CONVERGENCE_ON_AUTOBLOCKER">Convergence is not supported for meshes generated using methods MultiZone Quad/Tri or MultiZone Quad or Patch Independent</string>
  <string id="IDS_FA_INPUT_FAILURE_CONVERGENCE_ON_LINE_BODIES">Convergence is not supported for results on line bodies.</string>
  <string id="IDS_FA_INPUT_FAILURE_CONVERGENCE_WITH_PERIODICITY">Convergence is not supported for Symmetry models with Periodic Regions.</string>
  <string id="IDS_FA_INPUT_FAILURE__DARESULT_NOT_SUPPORTED">In Solution Combination Only Assessment analysis DA Results are supported only in Static, Transient and Explicit combinations.</string>
  <string id="IDS_FA_INPUT_FAILURE_INCORRECT_PROBE_TOOL_OUTPUT">You have elected to view more than one result selection on a probe scoped to a deformable body.  Deformable body probes can show only one result selection at a time. </string>
  <string id="IDS_FA_INPUT_FAILURE_INCORRECT_PROBE_TOOL_OUTPUT2">You have elected to view a result that is currently not supported for this type of probe or solver. </string>
  <string id="IDS_FA_INPUT_FAILURE_INCORRECT_PROBE_TOOL_EXPLICIT">You have elected to view more than one result selection on a probe scoped to a rigid body.  For an Explicit analysis, rigid body probes can show only one result selection at a time. </string>
  <string id="IDS_FA_INPUT_FAILURE_INVALID_MESH_SETTINGS_FOR_SHAPE">Lower order solid elements are not valid for the current analysis</string>
  <string id="IDS_FA_INPUT_FAILURE_JOINT__MISSING_GEOMETRY">Unspecified geometry in joint</string>
  <string id="IDS_FA_INPUT_FAILURE_JOINT__REQUIRES_JOINTCONDITION_THREE_ROTATIONS">You must specify joint conditions to all three rotational DOFs for one or more joints in the model. Please refer to the Troubleshooting section in the %PRODUCT_NAME Manual!</string>
  <string id="IDS_FA_INPUT_FAILURE_LARGE_DEFLECTION_OFF_WITH_HYPER">Material %1 has an active Hyperelastic property and Large Deflection is not being considered.


    Please either:
    a) Go to Analysis Settings Details and turn Large Deflection "On."
    b) Go to Engineering Data and suppress Hyperelastic material properties.
  </string>
  <string id="IDS_FA_INPUT_FAILURE_MATERIAL__HYPERELASTIC_MODEL_IS_INAPPLICABLE">Hyperelastic Material properties are not supported</string>
  <string id="IDS_FA_INPUT_FAILURE_SPRING__MISSING_GEOMETRY">Unspecified geometry in spring</string>
  <string id="IDS_FA_INPUT_FAILURE_SYMMETRY__UNKNOWN_COORDINATE_SYSTEM">You have symmetry object with incorrect coordinate system. The solution cannot proceed until this is fixed.</string>
  <string id="IDS_FA_INPUT_FAILURE__2D_Model_AXISYMMETRIC_Error">For a 2D model with axisymmetric behavior, the model must be on the positive X side of the XY plane. The CAD bounding box crosses to the negative side. To allow solving anyway, change Files --&gt; Options --&gt; Geometry --&gt; 2D Axisymmetric Check from Error to Warning. Part Transform can also be used to move the geometry to the positive side.</string>
  <string id="IDS_FA_INPUT_FAILURE__2D_Model_AXISYMMETRIC_Warn">For a 2D model with axisymmetric behavior, the model must be on the positive X side of the XY plane. The CAD bounding box crosses to the negative side. Part Transform can be used to move the geometry to the positive side.</string>
  <string id="IDS_FA_INPUT_FAILURE__ACCELERATION_MUST_BE_ACTIVE_THROUGH_ANALYSIS">Acceleration/Earth Gravity must be active throughout the analysis</string>
  <string id="IDS_FA_INPUT_WARNING__IMPORTED_CFD_PRESSURE_CGNS_FILE_DOES_NOT_EXIST">The cgns file does not exist in the provided file path.</string>
  <string id="IDS_FA_INPUT_FAILURE__IMPORTED_CFD_PRESSURE_COPY_CGNS_FILES">Failed to copy cgns files from the provided file path.</string>
  <string id="IDS_FA_INPUT_FAILURE__ACOUSTIC_EQV_SRC_SURF_IS_INVALID_WITH_NO_OPTION_OF_EQV_SRC_SURF_CONTROL">Far-field Radiation Surface is invalid with No option of Far-field Radiation Surface control.</string>
  <string id="IDS_FA_INPUT_FAILURE__ACOUSTIC_EQV_SRC_SURF_REQUIRED_FOR_MANUAL_OPTION_OF_EQV_SRC_SURF_CONTROL">Need at least one Far-field Radiation Surface for Manual option of Far-field Radiation Surface control.</string>
  <string id="IDS_FA_INPUT_FAILURE__ACOUSTIC_INCIDENT_WAVE_SRC_REQUIRED_FOR_ON_OPTION_OF_SCATTERING_FIELD_CONTROL">Need at least one Incident Wave Source for On option of Scattered Field Formulation control.</string>
  <string id="IDS_FA_INPUT_FAILURE__ACOUSTIC_INCIDENT_WAVE_SRC_WITH_INSIDE_MODEL_IS_INVALID_WITH_SCATTERED_OPTION_OF_SCATTERING_OUTPUT_TYPE">This is invalid option for Scattering controls. Please choose Total option as an Output type under Scattering controls.</string>
  <string id="IDS_FA_INPUT_FAILURE__FAR_FIELD_RESULT_IS_INVALID_WITH_NO_OPTION_OF_EQV_SRC_SURF_CONTROL">Far-field result is invalid with No option of Far-field Radiation Surface control.</string>
  <string id="IDS_FA_INPUT_FAILURE__DFSTL_IS_INVALID_WITHOUT_DIFFUSE_SOUND_FIELD_SOURCE">Diffuse Sound Transmission Loss result is invalid without Diffuse Sound Field source.</string>
  <string id="IDS_FA_INPUT_FAILURE__SYS_CPL_ERROR_ISSUE">For System-Coupling-Region scoped to volumes, the Nonlinear-Formulation property needs to use the 'Full' option.</string>
  <string id="IDS_FA_INPUT_FAILURE__TH_QUASI_MATERIAL_FIELD">Quasi option for Nonlinear-Formulation property is not supported with Imported Materials Field.</string>
  <string id="IDS_FA_INPUT_FAILURE__ANALYSIS_SETTING_TIME_STEPS">Invalid time step settings.  Please review inputs for all load steps.  You may use the worksheet view</string>
  <string id="IDS_FA_INPUT_FAILURE__INVALID_NAMED_SELECTION">The named selection specified for output selection is associated to the Nonlinear Adaptive Region, Geometry Based Adaptivity or SMART Crack Growth object. The results may not be available for scoped named selections if mesh is modified on those named selections scoping during solution.</string>
  <string id="IDS_FA_INPUT_FAILURE__SCOPED_NAMED_SELECTION_FOR_TOPOLOGY_OPTIMIZATION">This analysis has a future intent of Structural Optimization, the named selection specified for the Output Selection property under Analysis Settings of the current analysis will not apply to all the output controls.</string>
  <string id="IDS_FA_INPUT_FAILURE__BUCKLING_DISPLACEMENT">Displacements are not allowed in a buckling analysis.  Please see the buckling section in the %PRODUCT_NAME Help System for more information.</string>
  <string id="IDS_FA_INPUT_FAILURE__BUCKLING_THERMAL_LOAD">Thermal loads are not valid for the current analysis.</string>
  <string id="IDS_FA_INPUT_FAILURE__CFX_LICENSE_OR_INSTALLATION_PROBLEM">Features are incompatible with CFX license or installation</string>
  <string id="IDS_FA_INPUT_FAILURE__ANALYSIS_NOT_SUPPORTED_WITH_CONDENSED_GEOMETRY">The current analysis is not supported with condensed parts or imported condensed parts defined under the condensed geometry folder. If the condensed geometry object is not visible, please disable Environment Filtering to review and remove/suppress these objects from the Tree.</string>
  <string id="IDS_FA_INPUT_FAILURE__SUBSTRUCTURE_ANALYSIS_NOT_SUPPORTED_WITH_EXTERNAL_MODEL">Substructure Generation analysis with External Model is supported as a beta feature. Please turn on beta options to proceed with the solution.</string>
  <string id="IDS_FA_INPUT_FAILURE__JOINT_NOT_SUPPORTED">The assigned joint type is not supported for substructure analysis. Only fixed type joints are supported.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_OVERLAPPING_BODIES">Two Condensed Parts cannot scope to the same body</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_ELEMENT_ORIENTATION_WITH_OVERLAPPING_BODIES">This Condensed Part is invalid due to an Element Orientation spanning over a Condensed Part boundary.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_THICKNESS_WITH_OVERLAPPING_BODIES">This Condensed Part is invalid due to a Thickness spanning over a Condensed Part boundary.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_LAYERED_SECTION_WITH_OVERLAPPING_BODIES">This Condensed Part is invalid due to a Layered Section spanning over a Condensed Part boundary.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_WITH_INTERNAL_MPC_BUSHING_JOINT">This Condensed Part is invalid due to MPC formulation Bushing joint(s) completely contained inside the condensed part.</string>
  <string id="IDS_FA_INPUT_BETA_WARNING__CONDENSED_PART_WITH_INTERNAL_MPC_BUSHING_JOINT">MPC formulation Bushing joint(s) with command snippet completely contained inside the condensed part is a Beta feature.</string>
  <string id="IDS_FA_INPUT_WARNING__COMBI250_BUSHING_JOINT_WITH_RELATIVE_ROTATIONS_BETWEEN_ELEMENT_AND_REFERENCE_OR_MOBILE_COORDINATE_SYSTEMS">There is a relative rotation between selected Element and Reference/Mobile coordinate systems. Please review the results carefully.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_UNCONNECTED_BODIES">The bodies in a condensed part should be connected in some way</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_REINF_BODIES">Bodies with model type as Reinforcement can not be scoped to a condensed part.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_BEAMS_MOTION">Line bodies scoped to a Condensed Part or a Substructure Generation having Motion as Future Analysis are supported only if they have "Beam" Model Type, "Flexible" Stiffness Behavior, "Circular" Section Type, "Centroid" Offset Type and Linear Beam Elements.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_SHELLS_MOTION">Shell bodies with dimension set to 2D are not supported for Substructure analysis or Condensed Parts when the Future Analysis is set to Motion.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_MISSING_PREDICTED_INTERFACE">The software predicts required interfaces for this Condensed Part that are not in use.  Rerun the generation pass after issuing 'Detect Condensed Part Interfaces' to add them.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_TOO_FEW_MASTER_NODES">Only one master node is detected on the current condensed part. This is likely to result in a solver error. Please ensure that the condensed part interface has proper master node selection to avoid rigid body motion of the superelement region.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_TOO_MANY_MASTER_NODES">The total number of master nodes across all condensed parts are detected to be high. It is recommended that you define your condensed part interfaces such that the total number of masternodes are less than 10% of the nodes in the entire model or 3000 (whichever is lesser) to avoid slow solver performance.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_INTERFACE_INCORRECT_LOCATION">The interface selection does not share topology with the condensed part geometry</string>
  <string id="IDS_FA_INPUT_WARNING__SUPERELEMENT_REDUCED_MASTER_DOF">The total number of master degrees of freedom is reduced by the solver. This is probably due to internal constraint equations created by the solver interfering with master degrees of freedom specified in your model. Please check your model carefully for over constraints.</string>
  <string id="IDS_FA_INPUT_WARNING__SUPERELEMENT_SUPERSEDED_MASTER_DOF">Some of the master nodes is suppressed by specified constraints. Please check your model and review results carefully.</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_REACTIONS">The expansion pass does not show contribution of reactions from the nodes on the condensed parts as the reaction results are not stored for those nodes. Please review your results carefully.</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_WITH_NEW_CONNECTION_OBJECT_ADDED">Possible interface connection(s) object added / unsuppressed associated with this solved condensed part. Use 'Detect Condensed Part Interface' option to include these connection(s) as interface(s).</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_WITH_RIGID_REMOTE_INTERFACE">The Condensed Part defined in the model has remote type interface whose behavior is defined as Rigid. This may lead to over constraint and removal of master degrees of freedom.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_CONTACT_INTERFACE_DEFINED_ON_RIGID_BODY">The contact interface selection with rigid body topology is not valid</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_INTERFACE_INCORRECT_TOPOLOGY_TYPE">The interface selection topology type is not valid</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_INTERFACE_NOT_UNIQUE">An interface selection is not unique</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_INTERFACE_SUPPRESSED">An interface selection is suppressed</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_INTERFACE_IGNORED">A named selection interface is not sent to the solver.</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_INTERFACE_WITH_SHARED_TOPOLOGY">The condensed part has interface connections with shared topology, which are not considered in auto detection. Add applicable interfaces using named selection(s).</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_INTERFACE_WITH_SHARED_TOPOLOGY_MOTION">The condensed part scoping does not contain all shared topology bodies of a multibody part, which is not supported when generating for Motion Analysis.</string>
  <string id="IDS_FA_INPUT_INFO__CONDENSED_PART_INTERFACE_WITH_SHARED_TOPOLOGY_FROM_PULL">The condensed part is scoped to a body having shared interface derived from a pull operation and it must be added manually to the condensed part interfaces using Named Selection(s).</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_RBD_WITHOUT_CMS_REDUCTION">Component Mode Synthesis is required for an analysis target of Ansys Rigid Dynamics</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_NON_ZERO_DMPSTR">Constant Structural Damping Coefficient is not supported in modal analysis with Condensed Part.</string>
  <string id="IDS_FA_INPUT_FAILURE__ONDEMANDEXP_WITH_MODAL_DAMPED">On Demand Expansion is not supported with Damped solver.</string>
  <string id="IDS_FA_INPUT_FAILURE__ONDEMANDEXP_MSUPSTORAGE">On Demand Expansion is not supported with Store Results at All Frequencies set to No.</string>
  <string id="IDS_FA_INPUT_FAILURE__ONDEMANDEXP_STORE_RESULTS_POINTS">On Demand Expansion is not supported with Store Results At other than All Time Points.</string>
  <string id="IDS_FA_INPUT_WARNING__CONDENSED_PART_NON_ZERO_MP_DMPSTR">In the presence of Condensed Part, the modal analysis will ignore the material dependent constant structural damping coefficient defined in the Engineering Data.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONDENSED_PART_RBD_WITHOUT_FIXED_INTERFACE">Fixed interface is required for an analysis target of Ansys Rigid Dynamics</string>
  <string id="IDS_FA_INPUT_INFO__CONDENSED_PART_NO_DAMPING_DETECTED">The Program Controlled selection for "Generate Damping Matrix" property on one or more Condensed Parts does not generate the damping matrices because the damping related material properties are not defined on the scoped bodies or the connection objects internal to those condensed parts.</string>
  <string id="IDS_FA_INPUT_INFO__RES_PREDICT_DURING_SOLVE_WITHOUT_AI_PLUS_LICENSE">Resource Prediction during solve is set to Yes from Preferences, but your current license configuration does not allow performing resource prediction. Hence resource prediction is not performed.</string>
  <string id="IDS_FA_INPUT_FAILURE__INVALID_CMS_ANALYSIS_WITH_STATIC_CONDENSATION">Condensed part(s) with Matrix Reduction Method property set to Static Condensation are invalid for the current analysis type.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONNECTIONS_INVALID_IN_CURRENT_ANALYSIS">Connections are not allowed in the current analysis</string>
  <string id="IDS_FA_INPUT_FAILURE__CONTACT_INVALID_IN_TRANSIENT_RIGID">Contact regions are not allowed in the current analysis</string>
  <string id="IDS_FA_INPUT_FAILURE__CONVERGENCE_NEEDS_CALCULATE_VENG_ON">Use of convergence requires Volume and Energy to be set to Yes in Output Controls.</string>
  <string id="IDS_FA_INPUT_FAILURE__CONVERGENCE_NOT_ALLOWED_IN_LINKED_ENVIRONMENT">Convergence is not allowed in a linked environment</string>
  <string id="IDS_FA_INPUT_FAILURE__CONVERGENCE_USE_NOT_ALLOWED">Convergence is not allowed in the current analysis</string>
  <string id="IDS_FA_INPUT_FAILURE__CONVERGENCE_USE_NOT_ALLOWED_WITH_PLOT_TRACKER">Plot trackers are not supported in an analysis with convergence.</string>
  <string id="IDS_FA_INPUT_FAILURE__CMS_EXPANSION_MSUP">Expansion Settings aren't compatible with Expansion From Modal.</string>
  <string id="IDS_FA_INPUT_FAILURE__CORIOLIS_SUPPPORTS_ONLY_FULL_HARMONIC">Coriolis effect is not supported when the Solution Method property under the Analysis Settings is set to Mode Superposition.</string>
  <string id="IDS_FA_INPUT_FAILURE__SUBSTRUCTURE_CORIOLIS_ON_BUT_ROTVEL_OFF">You must define a Rotational Velocity in your model when you turn on Coriolis Effect.</string>
  <string id="IDS_FA_INPUT_FAILURE__DENSITY">You have a material with a zero density. The solution cannot proceed until this is fixed.</string>
  <string id="IDS_FA_INPUT_FAILURE__DIRECTIONLESS_LOAD">You have a load with an undefined direction. The solution cannot proceed until this is fixed.</string>
  <string id="IDS_FA_INPUT_FAILURE__DISTRIBUTED_SOLVE_ON">Distributed Solve is not valid for the current analysis.</string>
  <string id="IDS_FA_INPUT_FAILURE__ELECTRIC_RESISTIVITY">You have a conductor material with a zero resistivity. The solution cannot proceed until this is fixed.</string>
  <string id="IDS_FA_INPUT_FAILURE__DIRECT_FE_LOAD_NOT_SCOPED_TO_STRUCTURAL_REGION_NODES">Invalid scoping, select nodes of Structural / FSI region.</string>
  <string id="IDS_FA_INPUT_FAILURE__DIRECT_FE_LOAD_NOT_SCOPED_TO_PURELY_STRUCTURAL_REGION_NODES">Invalid scoping, select nodes of Structural region.</string>
  <string id="IDS_FA_INPUT_FAILURE__FREQUENCY_INPUT_IS_OUT_OF_BOUNDS">Frequency is out of bounds</string>
  <string id="IDS_FA_INPUT_FAILURE__INCORRECT_NB_OF_FARFIELD_MIC">The number of defined microphones must not be greater than 9.</string>
  <string id="IDS_FA_INPUT_FAILURE__RPM_SET_NB_WITH_MSUP_STORAGE">The Load Step Number requires Store Results At All Frequencies set to Yes in the Analysis Settings.</string>
  <string id="IDS_FA_INPUT_FAILURE__INCORRECT_STFT_END_TIME">Short Time Fourier Transform Start Time or End Time specified can't be greater than the analysis End Time.</string>
  <string id="IDS_FA_INPUT_FAILURE__INCORRECT_STFT_FREQUENCY_RESOLUTION">Mininimum Frequency Resolution must be lower than the Cutoff Frequency.</string>
  <string id="IDS_FA_INPUT_FAILURE__EXPLICIT_DYNAMICS_CURRENTLY_DOES_NOT_SUPPORT_FIBER_CSYS">The Solver Target currently does not support the Fiber Coordinate System.</string>
  <string id="IDS_FA_INPUT_FAILURE__LSDYNA_SOLUTION_COORDINATE_SYS_NOT_SUPPORTED">Only Beam results are supported in the Solution Coordinate System for an LS-DYNA Analysis.</string>
  <string id="IDS_FA_INPUT_FAILURE__SOLUTIONINTERVAL_INPUT_IS_OUT_OF_BOUNDS">The specified Set Number is out of bounds</string>
  <string id="IDS_FA_INPUT_FAILURE__MODE_INPUT_IS_OUT_OF_BOUNDS">Mode Number is out of bounds</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_MSUP_CLUSTERING_REQUIRES_DAMPING">Frequency clustering option requires at least one non-zero damping value on global alpha, global beta, global damping ratio or material damping ratio.</string>
  <string id="IDS_FA_INPUT_FAILURE__ALL_MODES_NOT_ALLOWED">All modes can be requested only when the Limit Search To Range property is set to Yes.</string>
  <string id="IDS_FA_INPUT_FAILURE__ALL_MODES_UNSUPPORTED_SOLVERTYPE">Program controlled or explicit solver selection of Direct, Subspace or Unsymmetric is supported for All modes selection.</string>
  <string id="IDS_FA_INPUT_WARNING__ALL_MODES_UNSUPPORTED_SOLVERTYPE">The current solver type selection is not supported when all modes are requested. Please select Direct, Subspace or Unsymmetric solver type in the Analysis Settings object.</string>
  <string id="IDS_FA_INPUT_FAILURE__NO_FOLLOWON_EXPANSION_FOR_CMS_WHEN_EQV_DAMPING_FROM_MODAL_SELECTED">For a CMS analysis, the Expand Results From property under Output Controls must be set to Modal Solution when the Eqv. Damping Ratio From Modal property under Damping Controls is set to Yes.</string>
  <string id="IDS_FA_INPUT_FAILURE__INVALID_EXPANSION_FROM_WITH_CONSTANT_DAMPING_RATIO">When Constant Damping Ratio is defined, the Expand Results From property under Output Controls must be set to Modal Solution.</string>
  <string id="IDS_FA_INPUT_INFO__OVERRIDE_NO_EQV_DAMPING_FROM_MODAL_SETTING">The Eqv. Damping Ratio From Modal property under Damping Controls is set to Yes as the constant damping coefficient is defined in the Engineering Data. Please remove or suppress the material damping coefficient if you do not wish to see the damping effects on your solution.</string>
  <string id="IDS_FA_WARNING__EQV_DAMPING_FROM_MODAL_SET_TO_NO_WITH_MP_DMPR_ON_ENGG_DATA">The material dependent damping ratio is defined in the Engineering Data for one or more materials used in the current model. The Eqv. Damping Ratio From Modal property under Damping Controls should be set to Yes if you wish to see the damping effects on your solution.</string>
  <string id="IDS_FA_WARNING__CRACK_FRONT_NODES_SET_TO_ZERO">The solver detected negligible crack extensions at some locations on the crack front during SMART crack growth for one of the cracks, and has set those values to zero.</string>
  <string id="IDS_FA_INPUT_FAILURE__MULTIPLE_STEPS_COUPLEDFIELD_HARMONIC">Multiple Steps option isn't available with current analysis physics.</string>
  <string id="IDS_FA_INPUT_FAILURE__STEP_VARYING_BASEEXCITATION">Step Varying option doesn't support Base Excitation.</string>
  <string id="IDS_FA_INPUT_FAILURE__SKIP_EXPANSION_AND_EXPANSION_FROM">On Demand Expansion option only support Expansion from Modal.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_INVALID_USER_FORCING_FREQUENCY_STEPS">User-defined frequency value should be non-zero positive value for each step.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_INVALID_USER_FORCING_FREQUENCY_STEPS_WITH_HARMONICVT">User-defined frequencies are not supported with the Solution Method property under the Analysis Settings is set to Variational Technology.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_INVALID_ORDER_BASED_WITH_HARMONICVT">Order based solve are not supported with the Solution Method property under the Analysis Settings set to Variational Technology.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_PHYSICS">Solution method set to Krylov under the analysis settings is supported only for pure acoustics physics system.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_CYCLIC_SYMMETRY">Solution method set to Krylov under the analysis settings is not supported when using Cyclic Region or Pre-Meshed Cyclic Region objects.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_LOAD">Incident Wave Source is not supported when the solution method is set to Krylov under the analysis settings.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_CONTACT">Normal Lagrange formulation in contacts is not supported when the solution method is set to Krylov under the analysis settings.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_REMOTE_POINT">The Formulation property is set to Lagrange Multiplier on at least one Remote Points or Joints, which is not supported when the solution method is set to Krylov under the analysis settings.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_MPC184">Only Fixed Joint with solver element type set to Contact/Direct or Bushing Joint with Bushing formulation are supported when the solution method is set to Krylov under the analysis settings.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_BEARING">Solution method set to Krylov under the analysis settings is not supported when Bearing definition is unsymmetric.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_CORIOLIS_EFFECT">Solution method set to Krylov under the analysis settings is not supported when Coriolis Effect is turned on.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_CORIOLIS_EFFECT_STATIC">Solution method set to Krylov under the analysis settings is not supported when Coriolis Effect is turned on in the linked static structural environment.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_KRYLOV_INVALID_NROPT">Solution method set to Krylov under the analysis settings is not supported when Newton-Raphson Option is set to Unsymmetric in the linked static structural environment.</string>
  <string id="IDS_FA_INPUT_FAILURE__IMPORTED_REMOTE_LOAD_INVALID_ORDER">The Orders property in the Imported Remote Loads object is empty or the Order entered does not exist in the upstream maxwell solution.</string>
  <string id="IDS_FA_INPUT_FAILURE__INVALID_HARMONIC_METHOD_MULTIPHYSICS">Solution method under the analysis settings set to Varaiational Technology is not supported for the physics combination in the current analysis.</string>
  <string id="IDS_FA_INPUT_FAILURE__NONLINEAR_BUCKLING_INVALID_WITH_PRESTRESS_THERMAL_COND">The prestress loading pattern cannot be retained for Buckling analysis when Thermal Condition is defined in the prestress analysis.</string>
  <string id="IDS_FA_INPUT_FAILURE__HARMONIC_INVALID_USER_FORCING_FREQUENCY_STEPS_WITH_CYCLIC_ANLYSIS">User-defined frequencies are not supported in cyclic analysis.</string>